/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Currency } from "./Currency";
import { CurrencyCountArgs } from "./CurrencyCountArgs";
import { CurrencyFindManyArgs } from "./CurrencyFindManyArgs";
import { CurrencyFindUniqueArgs } from "./CurrencyFindUniqueArgs";
import { CreateCurrencyArgs } from "./CreateCurrencyArgs";
import { UpdateCurrencyArgs } from "./UpdateCurrencyArgs";
import { DeleteCurrencyArgs } from "./DeleteCurrencyArgs";
import { PaymentMethodFindManyArgs } from "../../paymentMethod/base/PaymentMethodFindManyArgs";
import { PaymentMethod } from "../../paymentMethod/base/PaymentMethod";
import { PaymentFindManyArgs } from "../../payment/base/PaymentFindManyArgs";
import { Payment } from "../../payment/base/Payment";
import { CurrencyService } from "../currency.service";
@graphql.Resolver(() => Currency)
export class CurrencyResolverBase {
  constructor(protected readonly service: CurrencyService) {}

  async _currenciesMeta(
    @graphql.Args() args: CurrencyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Currency])
  async currencies(
    @graphql.Args() args: CurrencyFindManyArgs
  ): Promise<Currency[]> {
    return this.service.currencies(args);
  }

  @graphql.Query(() => Currency, { nullable: true })
  async currency(
    @graphql.Args() args: CurrencyFindUniqueArgs
  ): Promise<Currency | null> {
    const result = await this.service.currency(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Currency)
  async createCurrency(
    @graphql.Args() args: CreateCurrencyArgs
  ): Promise<Currency> {
    return await this.service.createCurrency({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Currency)
  async updateCurrency(
    @graphql.Args() args: UpdateCurrencyArgs
  ): Promise<Currency | null> {
    try {
      return await this.service.updateCurrency({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Currency)
  async deleteCurrency(
    @graphql.Args() args: DeleteCurrencyArgs
  ): Promise<Currency | null> {
    try {
      return await this.service.deleteCurrency(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [PaymentMethod], { name: "paymentMethods" })
  async findPaymentMethods(
    @graphql.Parent() parent: Currency,
    @graphql.Args() args: PaymentMethodFindManyArgs
  ): Promise<PaymentMethod[]> {
    const results = await this.service.findPaymentMethods(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Payment], { name: "payments" })
  async findPayments(
    @graphql.Parent() parent: Currency,
    @graphql.Args() args: PaymentFindManyArgs
  ): Promise<Payment[]> {
    const results = await this.service.findPayments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
