/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PaymentMethodService } from "../paymentMethod.service";
import { PaymentMethodCreateInput } from "./PaymentMethodCreateInput";
import { PaymentMethod } from "./PaymentMethod";
import { PaymentMethodFindManyArgs } from "./PaymentMethodFindManyArgs";
import { PaymentMethodWhereUniqueInput } from "./PaymentMethodWhereUniqueInput";
import { PaymentMethodUpdateInput } from "./PaymentMethodUpdateInput";
import { PaymentFindManyArgs } from "../../payment/base/PaymentFindManyArgs";
import { Payment } from "../../payment/base/Payment";
import { PaymentWhereUniqueInput } from "../../payment/base/PaymentWhereUniqueInput";

export class PaymentMethodControllerBase {
  constructor(protected readonly service: PaymentMethodService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PaymentMethod })
  async createPaymentMethod(
    @common.Body() data: PaymentMethodCreateInput
  ): Promise<PaymentMethod> {
    return await this.service.createPaymentMethod({
      data: {
        ...data,

        currency: data.currency
          ? {
              connect: data.currency,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        currency: {
          select: {
            id: true,
          },
        },

        description: true,
        id: true,
        name: true,
        smsExtractor: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PaymentMethod] })
  @ApiNestedQuery(PaymentMethodFindManyArgs)
  async paymentMethods(
    @common.Req() request: Request
  ): Promise<PaymentMethod[]> {
    const args = plainToClass(PaymentMethodFindManyArgs, request.query);
    return this.service.paymentMethods({
      ...args,
      select: {
        createdAt: true,

        currency: {
          select: {
            id: true,
          },
        },

        description: true,
        id: true,
        name: true,
        smsExtractor: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PaymentMethod })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async paymentMethod(
    @common.Param() params: PaymentMethodWhereUniqueInput
  ): Promise<PaymentMethod | null> {
    const result = await this.service.paymentMethod({
      where: params,
      select: {
        createdAt: true,

        currency: {
          select: {
            id: true,
          },
        },

        description: true,
        id: true,
        name: true,
        smsExtractor: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PaymentMethod })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePaymentMethod(
    @common.Param() params: PaymentMethodWhereUniqueInput,
    @common.Body() data: PaymentMethodUpdateInput
  ): Promise<PaymentMethod | null> {
    try {
      return await this.service.updatePaymentMethod({
        where: params,
        data: {
          ...data,

          currency: data.currency
            ? {
                connect: data.currency,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          currency: {
            select: {
              id: true,
            },
          },

          description: true,
          id: true,
          name: true,
          smsExtractor: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PaymentMethod })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePaymentMethod(
    @common.Param() params: PaymentMethodWhereUniqueInput
  ): Promise<PaymentMethod | null> {
    try {
      return await this.service.deletePaymentMethod({
        where: params,
        select: {
          createdAt: true,

          currency: {
            select: {
              id: true,
            },
          },

          description: true,
          id: true,
          name: true,
          smsExtractor: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/payments")
  @ApiNestedQuery(PaymentFindManyArgs)
  async findPayments(
    @common.Req() request: Request,
    @common.Param() params: PaymentMethodWhereUniqueInput
  ): Promise<Payment[]> {
    const query = plainToClass(PaymentFindManyArgs, request.query);
    const results = await this.service.findPayments(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,

        currency: {
          select: {
            id: true,
          },
        },

        id: true,

        paymentMethod: {
          select: {
            id: true,
          },
        },

        status: true,
        trxId: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/payments")
  async connectPayments(
    @common.Param() params: PaymentMethodWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        connect: body,
      },
    };
    await this.service.updatePaymentMethod({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/payments")
  async updatePayments(
    @common.Param() params: PaymentMethodWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        set: body,
      },
    };
    await this.service.updatePaymentMethod({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/payments")
  async disconnectPayments(
    @common.Param() params: PaymentMethodWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        disconnect: body,
      },
    };
    await this.service.updatePaymentMethod({
      where: params,
      data,
      select: { id: true },
    });
  }
}
